import { Team } from "./types";

const now = () => new Date().toISOString();

export const DEMO_TEAMS_20: Team[] = [
  {
    id: "t01",
    name: "三宿イーグルス",
    area: "世田谷・三宿",
    category: "U-12",
    level: 4,
    hasGround: false,
    bikeParking: "あり",
    uniformMain: "青",
    uniformSub: "白",
    rosterByGrade: { G1: 4, G2: 6, G3: 7, G4: 8, G5: 9, G6: 10 },
    desiredDates: ["2026-02-01", "2026-02-08", "2026-02-15"],
    note: "土曜午前が多い",
    updatedAt: now(),
  },
  {
    id: "t02",
    name: "下北沢ユナイテッド",
    area: "世田谷・下北沢",
    category: "U-12",
    level: 5,
    hasGround: true,
    bikeParking: "あり",
    uniformMain: "赤",
    uniformSub: "黒",
    rosterByGrade: { G1: 3, G2: 5, G3: 6, G4: 7, G5: 8, G6: 9 },
    desiredDates: ["2026-02-08", "2026-02-22"],
    note: "",
    updatedAt: now(),
  },
  {
    id: "t03",
    name: "駒沢ファイターズ",
    area: "世田谷・駒沢",
    category: "U-12",
    level: 6,
    hasGround: true,
    bikeParking: "なし",
    uniformMain: "黄",
    uniformSub: "青",
    rosterByGrade: { G1: 2, G2: 4, G3: 7, G4: 9, G5: 10, G6: 11 },
    desiredDates: ["2026-02-01", "2026-02-22"],
    note: "公式戦多め",
    updatedAt: now(),
  },
  {
    id: "t04",
    name: "目黒スターズ",
    area: "目黒",
    category: "U-12",
    level: 5,
    hasGround: false,
    bikeParking: "不明",
    uniformMain: "白",
    uniformSub: "紺",
    rosterByGrade: { G1: 2, G2: 3, G3: 4, G4: 5, G5: 6, G6: 8 },
    desiredDates: ["2026-02-15", "2026-02-22"],
    note: "",
    updatedAt: now(),
  },
  {
    id: "t05",
    name: "碑文谷キッズ",
    area: "目黒・碑文谷",
    category: "U-12",
    level: 3,
    hasGround: false,
    bikeParking: "あり",
    uniformMain: "緑",
    uniformSub: "白",
    rosterByGrade: { G1: 4, G2: 4, G3: 5, G4: 6, G5: 7, G6: 7 },
    desiredDates: ["2026-02-01", "2026-02-08"],
    note: "初心者多め",
    updatedAt: now(),
  },
  {
    id: "t06",
    name: "中野セントラル",
    area: "中野",
    category: "U-12",
    level: 7,
    hasGround: true,
    bikeParking: "あり",
    uniformMain: "黒",
    uniformSub: "白",
    rosterByGrade: { G1: 1, G2: 2, G3: 5, G4: 7, G5: 9, G6: 12 },
    desiredDates: ["2026-02-08", "2026-02-15"],
    note: "強度高め",
    updatedAt: now(),
  },
  // 7〜20（簡略：同パターンで埋め）
  ...Array.from({ length: 14 }).map((_, i) => {
    const n = i + 7;
    return {
      id: `t${String(n).padStart(2, "0")}`,
      name: `デモチーム${n}`,
      area: n % 2 === 0 ? "渋谷" : "世田谷",
      category: "U-12",
      level: (n % 7) + 3,
      hasGround: n % 3 === 0,
      bikeParking: n % 4 === 0 ? "なし" : "あり",
      uniformMain: n % 2 === 0 ? "青" : "赤",
      uniformSub: n % 2 === 0 ? "白" : "黒",
      rosterByGrade: {
        G1: (n % 4) + 2,
        G2: (n % 5) + 3,
        G3: (n % 6) + 4,
        G4: (n % 7) + 5,
        G5: (n % 8) + 6,
        G6: (n % 9) + 7,
      },
      desiredDates: n % 2 === 0 ? ["2026-02-08", "2026-02-22"] : ["2026-02-01", "2026-02-15"],
      note: "",
      updatedAt: now(),
    };
  }),
];