import { parseGenericTable, type TeamRow } from "./generic-table.ts";

const TOKYO_T_2026: Record<string, string[]> = {
  T1: [
    "トッカーノ",
    "Consorte A",
    "STFC",
    "AZ86東京青梅",
    "FC町田ゼルビア",
    "FC杉野",
    "ノールチシティ",
    "インテリオール",
  ],
  T2: [
    "すみだSC",
    "V AJUNT",
    "tfa",
    "norden",
    "Forza'02B",
    "FC多摩B",
    "クリアージュA",
    "修徳中学校",
    "東京久留米FC",
    "オーパスワン",
    "多摩大目黒",
    "コンフィアール町田",
    "PELADA",
    "FC VIDA",
    "駿台学園",
    "府ロク",
    "東京SC",
    "トレーロス",
    "三鷹CF",
    "トリプレッタB",
    "FRIENDLY",
    "TUソレイユ",
    "ピースユナイテッド",
    "かえつ有明中学校",
    "インテルアカデミー",
    "町田JFC",
    "サルヴァトーレ",
    "DESEL TOKYO",
    "FC GONA",
    "杉並ソシオ",
    "エスフォルソ",
    "F.TRES",
    "ジェファB",
    "FC渋谷",
    "GIUSTI",
    "日本大学第３中学校",
    "大森FC",
    "プログレッソ",
    "VEDIALO",
  ],
  T3: [
    "緑山SC",
    "暁星中学校",
    "GLORIA",
    "FC千代田",
    "ベルテール",
    "東京久留米FCB",
    "ARTE八王子",
    "BOBBIT TOKYO",
    "LARGO",
    "GAFC",
    "東海大菅生中学校",
    "東京都市大",
    "Branco八王子",
    "レッドスター",
    "バルサアカデミー",
    "AVIENTO",
    "バディSC",
    "SC Azuride Tokyo",
    "FC GABE",
    "FC目黒",
    "杉並ソシオB",
    "SHUGAKU",
    "OSA",
    "POMBA立川",
    "すみだSCB",
    "アローレ八王子",
    "石神井マメックス",
    "ConsorteB",
    "本郷中学校",
    "RIO FC",
    "MIP",
    "ボンフィン豊島",
    "VIGORE",
    "ヴェルメリオ",
    "世田谷FC",
    "Nexo Tokyo",
    "EURO FA",
    "クリアージュB",
    "プラミーゴ",
    "青梅FC",
    "杉並アヤックス",
    "スポルティング品川",
    "バリオーレ",
    "エリース東京",
    "FC.VIDA B",
    "エルシエロ",
    "国学院久我山中学校",
    "攻玉社中学校",
    "CSA",
    "両国FC",
    "GLAUNA",
    "調布FC",
    "九曜FC",
    "カフリンガ東久留米",
    "南葛SC",
    "府ロクB",
    "成城中学校",
  ],
  T4: [
    "LSS MITAKA",
    "バジェーナブランカ",
    "FC COAST",
    "明治大学明治中学校",
    "JOGAR",
    "ロッソ",
    "国分寺第５中学校",
    "プロメテウス",
    "Weiss Blau MITAKA",
    "アミーゴ",
    "RENATO",
    "東京小山FC",
    "あきる野FC",
    "Almundo",
    "S-JUEGO",
    "AZALEA",
    "両国FC B",
    "Visfida",
    "FC千代田B",
    "ONZE",
    "NOSSO",
    "Criacao shinjuku",
    "レスチ西ヶ丘",
    "東京都市大等々力",
    "東京シティ",
    "レガウ",
    "FC駒沢",
    "スクデット",
    "DIOS",
    "ナサロット",
    "東京２３FC",
    "湾岸ローカルズ",
    "ワンセンス武蔵野",
    "ヴェルメリオB",
    "ZEUS",
    "ヴィルトゥス",
    "エスフォルソB",
    "国分寺FA",
    "アンビシオン",
    "OLE KUNITACHI",
    "ASCOLTA",
    "OSC東京大泉",
    "成立学園",
    "杉並FC",
    "インテリオールB",
    "青山SC",
    "東京成徳中学校",
    "東京チャンプ",
    "FRIENDLY B",
    "FC江東",
    "清瀬VALIANT",
    "REGALO",
    "ZEAL TOKYO",
    "SIEG",
    "GIUSTI B",
  ],
};

function leagueKey(leagueName: string) {
  const t = String(leagueName || "").toUpperCase();
  if (t.includes("T1")) return "T1";
  if (t.includes("T2")) return "T2";
  if (t.includes("T3")) return "T3";
  if (t.includes("T4")) return "T4";
  return "";
}

export async function parseTokyoCY(
  html: string,
  leagueName: string,
): Promise<TeamRow[]> {
  const key = leagueKey(leagueName);

  if (key && TOKYO_T_2026[key]) {
    return TOKYO_T_2026[key].map((teamName) => ({
      teamName,
      leagueName,
    }));
  }

  return await parseGenericTable(html, leagueName);
}